server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: article_module
          uri: http://localhost:9090/
          predicates:
            - Path=/v1/articles/**
          filters:
            - RewritePath=/v1/(?<segment>.*), /$\{segment}
